// src/pages/TermsOfUse.jsx
import React, { useEffect } from 'react';

export default function TermsOfUse() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-[#070b12] text-gray-300 font-mono selection:bg-cyan-500/30 selection:text-cyan-400 py-12 md:py-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-[1000px] mx-auto bg-[#0d1424]/40 border border-cyan-500/10 rounded-2xl p-6 md:p-12 shadow-[0_0_60px_rgba(6,182,212,0.03)] backdrop-blur-sm">
        
        {/* --- PAGE HEADER (Dx.app Style Minimalist & Sharp) --- */}
        <div className="border-b border-neutral-800 pb-6 mb-8 text-left">
          <h1 className="text-2xl md:text-4xl font-black text-white tracking-wide uppercase">
            Terms & Conditions of Use
          </h1>
          <p className="text-xs md:text-sm text-cyan-400 mt-2 tracking-wider">
            Soltchain Technologies Ecosystem Matrix — Indian Legal Framework Compliance
          </p>
        </div>

        {/* --- LEGAL CONTENT MATRIX --- */}
        <div className="space-y-8 text-xs md:text-sm text-gray-400 leading-relaxed text-justify">
          
          {/* ⚠️ HIGH IMPORTANCE INTRODUCTORY NOTICE */}
          <p className="text-gray-200 font-medium">
            These website terms and conditions constitute a binding electronic record under the Information Technology Act, 2000 and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. These terms should be read by you (the "User," "Users," "you") in its entirety prior to your use of SoltHub's service, Soltcoin assets, or any utility products deployed by Soltchain Technologies ("Company," "we," "us," "our").
          </p>

          <div className="bg-pink-500/5 border border-pink-500/20 p-5 rounded-xl text-pink-400 font-bold text-xs uppercase tracking-wide leading-normal">
            BY USING THIS WEBSITE AND ENGAGING WITH THE SOLTHUB SMART CONTRACT INTERFACE, YOU ACCEPT AND AGREE TO BE BOUND AND COMPLY WITH THESE TERMS AND CONDITIONS AND OUR PRIVACY POLICY (COMPLIANT WITH THE DIGITAL PERSONAL DATA PROTECTION ACT, 2023). IF YOU DO NOT AGREE, YOU MUST NOT ACCESS THE WEBSITE OR DEPLOY ASSETS.
          </div>

          {/* SECTION 1 */}
          <div className="space-y-3">
            <h3 className="text-white font-bold text-sm md:text-base uppercase tracking-wider border-l-2 border-cyan-500 pl-3">
              Modifications to the Terms and Conditions and to the Website
            </h3>
            <p>
              We reserve the right in our sole discretion to revise and update these Terms and Conditions from time to time. Any and all such modifications are effective immediately upon posting and apply to all access to and continued use of the Website. You agree to periodically review the Terms and Conditions in order to be aware of any such modifications and your continued use shall be your acceptance of these. 
            </p>
            <p>
              The information and material on this Website, including launchpad parameter setups, staking rates, and advertisement fee matrices, may be changed, withdrawn, or terminated at any time in our sole discretion without notice. We will not be liable if, for any reason, all or any part of the Website is unavailable at any time or for any period.
            </p>
          </div>

          {/* SECTION 2 */}
          <div className="space-y-3">
            <h3 className="text-white font-bold text-sm md:text-base uppercase tracking-wider border-l-2 border-cyan-500 pl-3">
              Intellectual Property Rights and Ownership
            </h3>
            <p>
              You understand and agree that the Website and its entire contents, features, and functionality, including, but not limited to, all information, software, SoltDex engine code, smart contract logic, technology, text, displays, graphics, presentation, selection, and arrangement, are owned by Soltchain Technologies, its licensors, or other providers of such material and are protected by Indian and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
            </p>
            <p>
              The Company name, the term <span className="text-cyan-400 font-semibold">SoltHub</span>, <span className="text-cyan-400 font-semibold">Soltcoin</span>, the proprietary tickers, ecosystem logos, and all related product and service names, designs, and slogans are trademarks of the Company or its affiliates. You must not use such marks without the prior written permission of Soltchain Technologies.
            </p>
            <div className="pl-4 space-y-2 mt-2 border-l border-neutral-800 text-xs text-gray-400">
              <p><strong className="text-pink-500/90">(a)</strong> your computer terminal and decentralized wallet browser infrastructure may temporarily store or cache copies of data fragments being accessed and viewed;</p>
              <p><strong className="text-pink-500/90">(b)</strong> a reasonable number of dashboard logs for internal accounting and verification use only may be stored keeping any proprietary notices intact;</p>
              <p><strong className="text-pink-500/90">(c)</strong> metadata payloads downloaded directly from the non-custodial pipeline for specific personal, non-commercial decentralized operations.</p>
            </div>
          </div>

          {/* SECTION 3 */}
          <div className="space-y-3">
            <h3 className="text-white font-bold text-sm md:text-base uppercase tracking-wider border-l-2 border-cyan-500 pl-3">
              Conditions of Use & Ecosystem Protection
            </h3>
            <p>
              As a condition of your access and use, you agree that you may use the Website and SoltHub utilities only for lawful purposes. You warrant and agree that your use of the Website shall not:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-gray-400">
              <li>In any manner violate any applicable federal, state, local, or international law or regulation under the Indian Legal Framework, including guidelines issued by the Ministry of Electronics and Information Technology (MeitY).</li>
              <li>Include or route any graphic banners or hyperlinks inside sponsored header slots that are exploitive, obscene, harmful, phishing mirrors, or contain malicious scripts engineered to hijack decentralized Web3 wallets.</li>
              <li>Involve, provide, or contribute any false, inaccurate, or misleading parameters during token creation, staking deployments, or network routing events.</li>
              <li>Impersonate or attempt to impersonate Soltchain Technologies, a core developer, or another verified Web3 entity.</li>
            </ul>
          </div>
          {/* SECTION 4 (THE CRITICAL CRYTPO PROHIBITED USES CLAUSE WITH INDIAN REGULATIONS) */}
          <div className="space-y-3">
            <h3 className="text-white font-bold text-sm md:text-base uppercase tracking-wider border-l-2 border-cyan-500 pl-3">
              Prohibited Jurisdictions, Exploits & Taxation Compliance
            </h3>
            <p>
              The Website is provided on an automated, non-custodial network structure. Any exploitation of the system interface, smart contract bugs, flash-loan manipulation anomalies, or errors in program logic and/or Solidity code constitutes a material breach of these Terms. Any funds, including Soltcoin or associated tokens, a user may misappropriate or extract in this manner pursuant to this clause shall be considered void and the immediate recovery property of the Company, without limit.
            </p>
            <p className="border border-neutral-800 bg-neutral-900/30 p-4 rounded-xl text-gray-300 border-l-4 border-pink-500">
              <strong>VIRTUAL DIGITAL ASSETS (VDA) TAXATION & COMPLIANCE:</strong> Users interacting from India explicitly acknowledge that Virtual Digital Assets (VDAs) are subject to specific taxation laws under the Income Tax Act, 1961 (including Section 115BBH for 30% tax on VDA income and Section 194S for TDS obligations, where applicable). Users are solely responsible for reporting and paying all applicable taxes to the Government of India. 
            </p>
            <p>
              Persons located in or residents of any jurisdiction in which it is prohibited by systemic legislation from interacting with decentralized protocols (the "Prohibited Jurisdictions") are not permitted to make use of the Website or purchase Soltcoin. Any attempt to circumvent restrictions by manipulating RPC networks or VPN interfaces is a direct breach of this contract.
            </p>
          </div>

          {/* SECTION 5 */}
          <div className="space-y-3">
            <h3 className="text-white font-bold text-sm md:text-base uppercase tracking-wider border-l-2 border-cyan-500 pl-3">
              Disclaimer of Warranties & Market Volatility
            </h3>
            <div className="text-[11px] md:text-xs text-gray-400 bg-black/30 p-4 rounded-xl border border-neutral-800 space-y-2 uppercase font-sans tracking-wide">
              <p>YOU UNDERSTAND AND AGREE THAT YOUR USE OF SOLTHUB, ITS CONTENT, AND ANY DECENTRALIZED OPERATIONS FOUND OR ATTAINED THROUGH THE PLATFORM IS AT YOUR OWN RISK. THE INTERFACE AND SMART CONTRACT SCRIPTS ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.</p>
              <p>CRYPTOCURRENCY VALUES FLUCTUATE GREATLY. YOU EXPLICITLY HOLD SOLTCHAIN TECHNOLOGIES HARMLESS FOR ANY FINANCIAL IMPAIRMENTS, IMPERMANENT LOSS, GAS SPIKES, OR LIQUIDATION EVENTS OCCURRING DUE TO BLOCKCHAIN OUTAGES OR MARKET DRAWDOWNS.</p>
            </div>
          </div>

          {/* SECTION 6 */}
          <div className="space-y-3">
            <h3 className="text-white font-bold text-sm md:text-base uppercase tracking-wider border-l-2 border-cyan-500 pl-3">
              Limitation of Liability
            </h3>
            <p className="uppercase text-xs text-gray-500">
              UNDER NO CIRCUMSTANCE WILL THE COMPANY, ITS AFFILIATES, OR THEIR RESPECTIVE DIRECTORS, DEVELOPERS, OR SERVICE PROVIDERS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE INTERFACE LAYER, LIQUIDITY LOCKERS, OR STAKING MATRICES, INCLUDING LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF CRYPTOGRAPHIC TOKENS, EVEN IF FORESEEABLE.
            </p>
          </div>

          {/* SECTION 7 */}
          <div className="space-y-3">
            <h3 className="text-white font-bold text-sm md:text-base uppercase tracking-wider border-l-2 border-cyan-500 pl-3">
              Decentralized KYC and AML Disclaimers
            </h3>
            <p>
              SoltHub operates as a permissionless, fully decentralized environment for smart contract token interactions, advertising slot acquisition, and cryptographic engine allocation. As an open-source software development framework, Soltchain Technologies does not operate a centralized custody layer and has no systemic capability to enforce identity verification (KYC) mechanisms by default. Users are fully obligated to comply with all domestic anti-money laundering (AML) guidelines and Prevention of Money Laundering Act (PMLA), 2002 rules applicable to virtual digital assets in India.
            </p>
          </div>

          {/* SECTION 8 (INDIAN JURISDICTION SETTINGS) */}
          <div className="space-y-3">
            <h3 className="text-white font-bold text-sm md:text-base uppercase tracking-wider border-l-2 border-cyan-500 pl-3">
              Governing Law and Choice of Forum
            </h3>
            <p>
              The platform infrastructure, asset deployments, and these Terms and Conditions will be governed by, and construed in accordance with, the laws of the **Republic of India**, without giving effect to any choice or conflict of law principles. 
            </p>
            <p>
              Any legal action, dispute, or proceeding arising out of or relating to Soltchain Technologies, its smart contracts, or this platform will be instituted exclusively in the competent courts located in **New Delhi, India**, and each user irrevocably submits to the exclusive jurisdiction of such courts.
            </p>
          </div>

          {/* FOOTER ENTIRE AGREEMENT */}
          <p className="text-xs pt-4 border-t border-neutral-800 text-gray-500 italic">
            The Terms and Conditions and our automated code infrastructure constitute the sole and entire agreement between you and Soltchain Technologies regarding your navigation of SoltHub. 
            For compliance frameworks, grievance handling under the IT Act, or technical protocol inquiries, contact code channels at: <span className="text-cyan-400 not-italic">support@soltchain.network</span>
          </p>

        </div>
      </div>
    </div>
  );
}